# file: roles/nginx/tasks/main.yml

- name: Remove Apache
  yum: name=httpd state=absent
  ignore_errors: yes
- name: Install nginx
  yum: name=nginx state=latest
- name: Delete defauls
  file: name={{ item }} state=absent
  with_items:
    - /etc/nginx/conf.d/default.conf
    - /etc/nginx/conf.d/ssl.conf
    - /etc/nginx/conf.d/virtual.conf
  ignore_errors: yes
- name: Create vhost directories
  file: path={{ item }} owner=root group=root mode=755 state=directory
  with_items:
    - /etc/nginx/vhost-available
    - /etc/nginx/vhost-enabled
- name: Copy upstream-servers.conf
  copy: src=../files/upstream-servers.conf dest=/etc/nginx/conf.d/ owner=root group=root mode=644
- name: Copy include-vhosts.conf
  copy: src=../files/include-vhosts.conf dest=/etc/nginx/conf.d/ owner=root group=root mode=644
- name: Copy default.vhost
  copy: src=../files/default.vhost dest=/etc/nginx/vhost-available/ owner=root group=root mode=644
- name: Link default.vhost
  file: src=/etc/nginx/vhost-available/default.vhost dest=/etc/nginx/vhost-enabled/default.vhost state=link
- name: Start and enable nginx
  service: name=nginx enabled=yes state=started
