- hosts: all
  tasks:
  - name: install nginx
    yum: name=nginx state=latest
  - name: start nginx
    service: name=nginx state=started
  - name: delete iptables default rules
    file: path=/etc/sysconfig/iptables state=absent
  - name: flush iptables default rules
    command: /sbin/iptables -F
  - name: remove yum-autoupdate
    yum: name=yum-autoupdate state=absent
  - name: create cron for automatic ansible-pull
    command: echo '*/5 * * * * root ansible-pull -U https://github.com/dcodix/simple-test-ansible-pull.git -d /tmp/playbooks' > /etc/cron.d/ansible-pull
