# file: roles/ssh-keys/tasks/main.yml

- name: Create user testuser
  user: name=testuser state=present
- name: Create .ssh directory
  file: path=/home/testuser/.ssh owner=testuser group=testuser mode=700 state=directory
- name: Copy pubkey
  copy: src=../files/id_rsa.pub dest=/home/testuser/.ssh/ owner=testuser group=testuser mode=644
- name: Copy privkey
  copy: src=../files/id_rsa dest=/home/testuser/.ssh/ owner=testuser group=testuser mode=600
