# file: roles/common/tasks/main.yml

- name: Install nmap
  yum: name=nmap state=latest
- name: Remove yum-autoupdate
  yum: name=yum-autoupdate state=absent
#- name: yum update
#  yum: name=* state=latest
